apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.faltioServiceAccount.name }}
  namespace: {{ .Values.faltioServiceAccount.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: faltio-role
  namespace: {{ .Values.faltioServiceAccount.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices","inferenceservices/status"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["faltio.io"]
    resources: ["faltiodeployments", "faltiodeployments/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: faltio-rolebinding
  namespace: {{ .Values.faltioServiceAccount.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.faltioServiceAccount.name }}
    namespace: {{ .Values.faltioServiceAccount.namespace }}
roleRef:
  kind: Role
  name: faltio-role
  apiGroup: rbac.authorization.k8s.io
