apiVersion: v1
kind: ServiceAccount
metadata:
  name: faltio-operator
  namespace: faltio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: faltio-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "secrets", "persistentvolumeclaims", "persistentvolumes", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["faltio.io"]
    resources: ["faltiodeployments", "faltiodeployments/status", "faltiodeployments/finalizers"]
    verbs: ["*"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: faltio-operator-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: faltio-operator-role
  apiGroup: rbac.authorization.k8s.io
